AgentXcpp: agentxcpp::AddAgentCapsPDU Class Reference
agentxcpp::AddAgentCapsPDU Class Reference
Represents an AddAgentCaps-PDU.
#include <AddAgentCapsPDU.hpp>
Public Member Functions
AddAgentCapsPDU (binary::const_iterator &pos, const binary::const_iterator &end, bool big_endian)
Parse constructor.
AddAgentCapsPDU ()
Default Constructor.
AddAgentCapsPDU (Oid id, OctetStringVariable descr)
Constructor.
void set_id (Oid id)
Set the id field.
Oid get_id ()
Get the id field.
void set_descr (OctetStringVariable descr)
Set the descr field.
OctetStringVariable get_descr ()
Get the descr field.
virtual binary serialize ()
Serialize the PDU.
Public Member Functions inherited from agentxcpp::PDUwithContext
bool has_context ()
Whether the PDU has a context.
OctetStringVariable get_context ()
Get context.
void set_context (OctetStringVariable value)
Set the PDU's context.
void remove_context ()
Removes the context from the PDU.
Public Member Functions inherited from agentxcpp::PDU
virtual ~PDU ()
Destructor.
bool get_new_index ()
Get new_index flag.
void set_new_index (bool new_index)
Set new_index flag.
bool get_any_index ()
Get any_index flag.
void set_any_index (bool any_index)
Set any_index flag.
quint32 get_sessionID ()
Get sessionID.
void set_sessionID (quint32 id)
Set sessionID.
quint32 get_transactionID ()
Get transactionID.
void set_transactionID (quint32 id)
Set transactionID.
quint32 get_packetID ()
Get packetID.
void set_packetID (quint32 packetID)
Set packetID.
virtual binary serialize () const =0
Serialize function for concrete PDUs.
Private Attributes
Oid id
The Object Identifier containing the value of an invocation of the AGENT-CAPABILITIES macro.
OctetStringVariable descr
An Octet String containing a DisplayString to be used as the value of sysORDescr corresponding to the sysORID value above.
Additional Inherited Members
Static Public Member Functions inherited from agentxcpp::PDU
static QSharedPointer< PDU > parse_pdu (binary buf)
Parse a PDU from a buffer.
Protected Types inherited from agentxcpp::PDU
enum type_t {
agentxOpenPDU = 1, agentxClosePDU = 2, agentxRegisterPDU = 3, agentxUnregisterPDU = 4,
agentxGetPDU = 5, agentxGetNextPDU = 6, agentxGetBulkPDU = 7, agentxTestSetPDU = 8,
agentxCommitSetPDU = 9, agentxUndoSetPDU = 10, agentxCleanupSetPDU = 11, agentxNotifyPDU = 12,
agentxPingPDU = 13, agentxIndexAllocatePDU = 14, agentxIndexDeallocatePDU = 15, agentxAddAgentCapsPDU = 16,
agentxRemoveAgentCapsPDU = 17, agentxResponsePDU = 18
}
The PDU types.
Protected Member Functions inherited from agentxcpp::PDUwithContext
PDUwithContext (binary::const_iterator &pos, const binary::const_iterator &end, bool big_endian)
Parse constructor.
void add_header (type_t type, binary &payload) const
Add PDU header and context field to the payload.
PDUwithContext ()
Default Constructor.
Protected Member Functions inherited from agentxcpp::PDU
PDU (binary::const_iterator &pos, const binary::const_iterator &end, bool big_endian)
Parse constructor.
void add_header (type_t type, binary &payload) const
Construct the PDU header and add it to the payload.
PDU ()
Default constructor.
Protected Attributes inherited from agentxcpp::PDU
bool instance_registration
the instance_registration flag
bool non_default_context
Whether the PDU has a non-default context.
quint32 packetID
h.packetID field according to RFC 2741, 6.1. "AgentX PDU Header".
Detailed Description
Represents an AddAgentCaps-PDU.
Definition at line 33 of file AddAgentCapsPDU.hpp.
Constructor & Destructor Documentation
AddAgentCapsPDU::AddAgentCapsPDU (binary::const_iterator & pos, const binary::const_iterator & end, bool big_endian)
Parse constructor.
Construct the object by parsing a stream. See Parsing incoming PDUs for details about PDU parsing.
Parameters
pos Iterator pointing to the current stream position. The iterator is advanced while reading the header.
end Iterator pointing one element past the end of the current stream. This is needed to mark the end of the buffer.
big_endian Whether the serialized form of the PDU is in big_endian format.
Exceptions
parse_error If parsing fails, for example because reading the stream fails or the PDU is malformed.
Definition at line 26 of file AddAgentCapsPDU.cpp.
References descr, and agentxcpp::OidVariable::value().
agentxcpp::AddAgentCapsPDU::AddAgentCapsPDU () inline
Default Constructor.
Sets the state of the object to the defaults as set by the PDU::PDUwithContext() constructor. The fields 'id' and 'descr' are initialized to be empty.
Definition at line 87 of file AddAgentCapsPDU.hpp.
AddAgentCapsPDU::AddAgentCapsPDU (Oid id, OctetStringVariable descr)
Constructor.
Sets the state of the object to the defaults as set by the PDU::PDUwithContext() constructor. The fields id and descr are initialized according to the parameters.
Parameters
id The value of the id field.
descr The value of the descr field.
Definition at line 58 of file AddAgentCapsPDU.cpp.
References descr, and id.
Member Function Documentation
OctetStringVariable agentxcpp::AddAgentCapsPDU::get_descr () inline
Get the descr field.
Returns
The descr value.
Definition at line 137 of file AddAgentCapsPDU.hpp.
References descr.
Oid agentxcpp::AddAgentCapsPDU::get_id () inline
Get the id field.
Returns
The id value.
Definition at line 117 of file AddAgentCapsPDU.hpp.
References id.
binary AddAgentCapsPDU::serialize () virtual
Serialize the PDU.
Definition at line 42 of file AddAgentCapsPDU.cpp.
References agentxcpp::PDUwithContext::add_header(), agentxcpp::PDU::agentxAddAgentCapsPDU, descr, agentxcpp::OctetStringVariable::serialize(), and agentxcpp::OidVariable::serialize().
void agentxcpp::AddAgentCapsPDU::set_descr (OctetStringVariable descr) inline
Set the descr field.
Parameters
descr The new descr value.
Definition at line 127 of file AddAgentCapsPDU.hpp.
References descr.
void agentxcpp::AddAgentCapsPDU::set_id (Oid id) inline
Set the id field.
Parameters
id The new id value.
Definition at line 107 of file AddAgentCapsPDU.hpp.
References id.
Member Data Documentation
OctetStringVariable agentxcpp::AddAgentCapsPDU::descr private
An Octet String containing a DisplayString to be used as the value of sysORDescr corresponding to the sysORID value above.
See RFC 2741, 6.2.14. "The agentx-AddAgentCaps-PDU" for details.
Definition at line 52 of file AddAgentCapsPDU.hpp.
Referenced by AddAgentCapsPDU(), get_descr(), serialize(), and set_descr().
Oid agentxcpp::AddAgentCapsPDU::id private
The Object Identifier containing the value of an invocation of the AGENT-CAPABILITIES macro.
See RFC 2741, 6.2.14. "The agentx-AddAgentCaps-PDU" for details.
Definition at line 43 of file AddAgentCapsPDU.hpp.
Referenced by AddAgentCapsPDU(), get_id(), and set_id().
The documentation for this class was generated from the following files:
/home/tanjeff/projekte/agentxcpp/deliv/agentxcpp-0.3/src/AddAgentCapsPDU.hpp
/home/tanjeff/projekte/agentxcpp/deliv/agentxcpp-0.3/src/AddAgentCapsPDU.cpp