AgentXcpp: agentxcpp::IntegerVariable Class Reference
agentxcpp::IntegerVariable Class Reference
This class represents an Integer variable as described in RFC 2741.
#include <IntegerVariable.hpp>
Public Member Functions
IntegerVariable (qint32 _value=0)
Constructor.
virtual binary serialize () const
Encode the object as described in RFC 2741, section 5.4.
IntegerVariable (binary::const_iterator &pos, const binary::const_iterator &end, bool big_endian=true)
Parse Constructor.
virtual Oid toOid () const
Convert the value to an OID.
void setValue (qint32 _value)
Set the value.
virtual qint32 value ()
Get the current value.
virtual void handle_get ()
Handle a Get Request.
virtual void perform_get ()
Perform a Get request.
virtual testset_result_t handle_testset (QSharedPointer< AbstractVariable > _v)
Handle a TestSet request.
virtual testset_result_t perform_testset (qint32 _v)
Perform an SNMP TestSet request.
virtual void handle_cleanupset ()
Handle a CleanupSet request.
virtual void perform_cleanupset (qint32 _v)
Perform an SNMP CleanupSet request.
virtual bool handle_commitset ()
Handle a CommitSet request.
virtual bool perform_commitset (qint32 _v)
Perform an SNMP CommitSet request.
virtual bool handle_undoset ()
Handle an UndoSet request.
virtual bool perform_undoset (qint32 _v)
Perform an SNMP UndoSet request.
Public Member Functions inherited from agentxcpp::AbstractVariable
virtual ~AbstractVariable ()
Virtual destructor.
Protected Attributes
qint32 v
The current value.
Private Attributes
QSharedPointer< IntegerVariable > new_value
The new value for the variable. Used during a Set operation.
Additional Inherited Members
Public Types inherited from agentxcpp::AbstractVariable
enum testset_result_t {
noError = 0, genErr = 5, noAccess = 6, wrongType = 7,
wrongLength = 8, wrongValue = 10, noCreation = 11, inconsistentValue = 12,
resourceUnavailable = 13, notWritable = 17, inconsistentName = 18
}
Result type for the TestSet validation.
Detailed Description
This class represents an Integer variable as described in RFC 2741.
The page The Variable Objects explains how to use variables.
Note
When an IntegerVariable is used as INDEX within a table, it should never hold the value 0. This is because the value is then used as part of an OID, where 0 is forbidden (or at least discouraged).
Definition at line 41 of file IntegerVariable.hpp.
Constructor & Destructor Documentation
agentxcpp::IntegerVariable::IntegerVariable (qint32 _value = 0) inline
Constructor.
Creates an IntegerValue object.
Exceptions
None.
Definition at line 83 of file IntegerVariable.hpp.
IntegerVariable::IntegerVariable (binary::const_iterator & pos, const binary::const_iterator & end, bool big_endian = true)
Parse Constructor.
This constructor parses the serialized form of the object. It takes an iterator, starts parsing at the position of the iterator and advances the iterator to the position right behind the object.
The constructor expects valid data from the stream; if parsing fails, parse_error is thrown. In this case, the iterator position is undefined.
Parameters
pos Iterator pointing to the current stream position. The iterator is advanced while parsing.
end Iterator pointing one element past the end of the current stream. This is needed to avoid buffer overrun.
big_endian Whether the input stream is in big endian format.
Definition at line 36 of file IntegerVariable.cpp.
References agentxcpp::read32(), and v.
Member Function Documentation
virtual void agentxcpp::IntegerVariable::handle_cleanupset () inline virtual
Handle a CleanupSet request.
This function calls perform_cleanupset() with the internal value of new_value (which was updated by the last handle_testset() invocation).
Implements agentxcpp::AbstractVariable.
Definition at line 256 of file IntegerVariable.hpp.
References perform_cleanupset().
virtual bool agentxcpp::IntegerVariable::handle_commitset () inline virtual
Handle a CommitSet request.
This function calls perform_commitset() with the internal value of new_value (which was updated by the last handle_testset() invocation).
Returns
The return value of perform_commitset().
Implements agentxcpp::AbstractVariable.
Definition at line 290 of file IntegerVariable.hpp.
References perform_commitset().
virtual void agentxcpp::IntegerVariable::handle_get () inline virtual
Handle a Get Request.
This function calls perform_get() to update the internal value.
Implements agentxcpp::AbstractVariable.
Definition at line 174 of file IntegerVariable.hpp.
References perform_get().
virtual testset_result_t agentxcpp::IntegerVariable::handle_testset (QSharedPointer< AbstractVariable > _v) inline virtual
Handle a TestSet request.
This function converts the argument, stores it in new_value and then calls perform_testset() with the internal value of new_value. If conversion fails, AbstractVariable::wrongType is returned and perform_testset() is not called.
Parameters
_v The new value for the variable.
Returns
AbstractVariable::wrongType if the conversion fails. Otherwise, the result of perform_testset() is returned.
Implements agentxcpp::AbstractVariable.
Definition at line 206 of file IntegerVariable.hpp.
References perform_testset(), and agentxcpp::AbstractVariable::wrongType.
virtual bool agentxcpp::IntegerVariable::handle_undoset () inline virtual
Handle an UndoSet request.
This function calls perform_undoset() with the internal value of new_value (which was updated by the last handle_testset() invocation).
Returns
The return value of perform_undoset().
Implements agentxcpp::AbstractVariable.
Definition at line 326 of file IntegerVariable.hpp.
References perform_undoset().
virtual void agentxcpp::IntegerVariable::perform_cleanupset (qint32 _v) inline virtual
Perform an SNMP CleanupSet request.
This method is invoked when an SNMP CleanupSet request is received. It shall release any resources allocated by perform_testset().
The default implementation does nothing. If no action is required to perform the CleanupSet operation, this method need not be overridden.
Parameters
_v The value to which the variable was (possibly) set.
Definition at line 274 of file IntegerVariable.hpp.
Referenced by handle_cleanupset().
virtual bool agentxcpp::IntegerVariable::perform_commitset (qint32 _v) inline virtual
Perform an SNMP CommitSet request.
This method is invoked when an SNMP CommitSet request is received. It shall perform the actual write operation.
The default implementation returns false to indicate that the operation failed. To implement a writeable SNMP variable this method must be overridden.
Parameters
_v The value which shall be written.
Returns
True if the operation succeeded, false otherwise.
Definition at line 309 of file IntegerVariable.hpp.
Referenced by handle_commitset().
virtual void agentxcpp::IntegerVariable::perform_get () inline virtual
Perform a Get request.
This method is invoked when an SNMP Get request is received. It should update the internal value v.
Definition at line 185 of file IntegerVariable.hpp.
Referenced by handle_get().
virtual testset_result_t agentxcpp::IntegerVariable::perform_testset (qint32 _v) inline virtual
Perform an SNMP TestSet request.
This method is invoked when an SNMP TestSet request is received. It shall check whether a Set operation is possible for the variable. It shall acquire the resources needed to perform the Set operation (but the Set operation shall not yet be performed).
The default implementation returns AbstractVariable::noAccess to indicate that this is a read-only variable. Thus, for read-only variables this method need not be overridden.
Parameters
_v The new value provided by the master agent.
Returns
The result of the check (this is reported to the master agent).
Definition at line 242 of file IntegerVariable.hpp.
References agentxcpp::AbstractVariable::noAccess.
Referenced by handle_testset().
virtual bool agentxcpp::IntegerVariable::perform_undoset (qint32 _v) inline virtual
Perform an SNMP UndoSet request.
This method is invoked when an SNMP UndoSet request is received. It shall undo whatever perform_commitset() performed. It shall also release all resources allocated by perform_testset(), because perform_cleanupset() will not be called afterwards.
The default implementation returns false to indicate that the operation failed. It is strongly recommended that writeable variables override this method.
A default implementation is provided to allow implementing read-only variables.
Parameters
_v The value just set by perform_commitset().
Returns
True on success, false otherwise.
Definition at line 355 of file IntegerVariable.hpp.
Referenced by handle_undoset().
binary IntegerVariable::serialize () const virtual
Encode the object as described in RFC 2741, section 5.4.
This function uses big endian.
Implements agentxcpp::AbstractVariable.
Definition at line 25 of file IntegerVariable.cpp.
References v, and agentxcpp::write32().
void agentxcpp::IntegerVariable::setValue (qint32 _value) inline
Set the value.
Parameters
_value The new value.
Definition at line 151 of file IntegerVariable.hpp.
virtual Oid agentxcpp::IntegerVariable::toOid () const inline virtual
Convert the value to an OID.
The conversion is done according to RFC 2578, 7.7. "Mapping of the INDEX clause". The value is converted to an Oid with a single subid. Note that INTEGER values are signed, while subids are not. A negative value with be converted to a big unsigned subid.
This method should not be overridden.
Note
If an INTEGER is used in an INDEX clause, the value 0 should be avoided according to RFC 2578, 7.7. "Mapping of the INDEX clause".
Implements agentxcpp::AbstractVariable.
Definition at line 139 of file IntegerVariable.hpp.
virtual qint32 agentxcpp::IntegerVariable::value () inline virtual
Get the current value.
Returns
The value.
Definition at line 161 of file IntegerVariable.hpp.
References v.
Member Data Documentation
QSharedPointer<IntegerVariable> agentxcpp::IntegerVariable::new_value private
The new value for the variable. Used during a Set operation.
The Set operation is performed in up to four steps (TestSet, CommitSet, CleanupSet, UndoSet). Only the TestSet step actually receives the new value. This value is stored here so that it can be delivered to perform_commitset(), perform_undoset() and perform_cleanupset().
Definition at line 72 of file IntegerVariable.hpp.
qint32 agentxcpp::IntegerVariable::v protected
The current value.
This is the value which is sent to the master agent on SNMP Get requests. According to RFC 2578, INTEGER is a signed 32-bit number. The value can be obtained with value() and set with setValue().
The perform_get() method should update this member.
The methods perform_testset(), perform_commitset(), perform_cleanupset() and/or perform_undoset() may update this member, but it is not needed for proper function.
Definition at line 58 of file IntegerVariable.hpp.
Referenced by IntegerVariable(), serialize(), and value().
The documentation for this class was generated from the following files:
/home/tanjeff/projekte/agentxcpp/deliv/agentxcpp-0.3/src/IntegerVariable.hpp
/home/tanjeff/projekte/agentxcpp/deliv/agentxcpp-0.3/src/IntegerVariable.cpp