AgentXcpp: agentxcpp::DisplayStringVariable Class Reference
agentxcpp::DisplayStringVariable Class Reference
A DisplayString variable.
#include <DisplayStringVariable.hpp>
Public Member Functions
DisplayStringVariable (QString _value=QString())
(Default) constructor.
void setValue (QString _value)
Set the value of the variable.
QString value ()
Get the value of the variable.
Public Member Functions inherited from agentxcpp::OctetStringVariable
binary serialize () const
Encode the object as described in RFC 2741, section 5.3.
OctetStringVariable (binary _value=binary())
(Default) constructor.
OctetStringVariable (QString initial_value)
Construct object from a string.
OctetStringVariable (binary::const_iterator &pos, const binary::const_iterator &end, bool big_endian=true)
Parse Constructor.
void setValue (binary _value)
Set the value.
void setValue (QString _value)
Set the value.
binary value () const
Get the current value.
QString toString () const
Get the current value as string.
virtual Oid toOid () const
Convert the value to an OID.
virtual void handle_get ()
Handle a Get Request.
virtual void perform_get ()
Perform a Get request.
virtual testset_result_t handle_testset (QSharedPointer< AbstractVariable > _v)
Handle a TestSet request.
virtual testset_result_t perform_testset (const binary &_v)
Handle a TestSet request.
virtual void handle_cleanupset ()
Handle a CleanupSet request.
virtual void perform_cleanupset (const binary &_v)
Perform an SNMP CleanupSet request.
virtual bool handle_commitset ()
Handle a CommitSet request.
virtual bool perform_commitset (const binary &_v)
Perform an SNMP CommitSet request.
virtual bool handle_undoset ()
Handle an UndoSet request.
virtual bool perform_undoset (const binary &_v)
Perform an SNMP UndoSet request.
Public Member Functions inherited from agentxcpp::AbstractVariable
virtual ~AbstractVariable ()
Virtual destructor.
Additional Inherited Members
Public Types inherited from agentxcpp::AbstractVariable
enum testset_result_t {
noError = 0, genErr = 5, noAccess = 6, wrongType = 7,
wrongLength = 8, wrongValue = 10, noCreation = 11, inconsistentValue = 12,
resourceUnavailable = 13, notWritable = 17, inconsistentName = 18
}
Result type for the TestSet validation.
Protected Attributes inherited from agentxcpp::OctetStringVariable
binary v
The value.
Detailed Description
A DisplayString variable.
This class represent an SNMP variable with SYNTAX DisplatString. The data is stored and processed as an OctetStringVariable, but this class provides additional methods for easy string handling.
Definition at line 37 of file DisplayStringVariable.hpp.
Constructor & Destructor Documentation
agentxcpp::DisplayStringVariable::DisplayStringVariable (QString _value = QString()) inline
(Default) constructor.
Create a DisplayString variable.
Parameters
_value The initial value of the variable.
Exceptions
None.
Definition at line 51 of file DisplayStringVariable.hpp.
References agentxcpp::OctetStringVariable::setValue().
Member Function Documentation
void agentxcpp::DisplayStringVariable::setValue (QString _value) inline
Set the value of the variable.
Parameters
_value The new value.
Exceptions
None.
Definition at line 63 of file DisplayStringVariable.hpp.
References agentxcpp::OctetStringVariable::setValue().
QString agentxcpp::DisplayStringVariable::value () inline
Get the value of the variable.
Returns
The current value.
Exceptions
None.
Definition at line 75 of file DisplayStringVariable.hpp.
References agentxcpp::OctetStringVariable::toString().
The documentation for this class was generated from the following file:
/home/tanjeff/projekte/agentxcpp/deliv/agentxcpp-0.3/src/DisplayStringVariable.hpp