AgentXcpp: agentxcpp::OidVariable Class Reference
agentxcpp::OidVariable Class Reference
Represents an SNMP OBJECT-IDENTENTIFIER variable.
#include <OidVariable.hpp>
Public Member Functions
OidVariable (const Oid &o)
Initialize an OidVariable object with an Oid.
OidVariable ()
Default constructor.
Oid value ()
Get the current value.
void setValue (const Oid &_value)
Set the value.
binary serialize () const
Encode the object as described in RFC 2741, section 5.4.
OidVariable (binary::const_iterator &pos, const binary::const_iterator &end, bool big_endian=true)
Parse Constructor.
virtual Oid toOid () const
Convert the value to an OID.
virtual void handle_get ()
Handle a Get Request.
virtual void perform_get ()
Perform a Get request.
virtual testset_result_t handle_testset (QSharedPointer< AbstractVariable > _v)
Handle a TestSet request.
virtual testset_result_t perform_testset (const Oid &_v)
Perform an SNMP TestSet request.
virtual void handle_cleanupset ()
Handle a CleanupSet request.
virtual void perform_cleanupset (const Oid &_v)
Perform an SNMP CleanupSet request.
virtual bool handle_commitset ()
Handle a CommitSet request.
virtual bool perform_commitset (const Oid &_v)
Perform an SNMP CommitSet request.
virtual bool handle_undoset ()
Handle an UndoSet request.
virtual bool perform_undoset (const Oid &_v)
Perform an SNMP UndoSet request.
Public Member Functions inherited from agentxcpp::AbstractVariable
virtual ~AbstractVariable ()
Virtual destructor.
Protected Attributes
Oid v
The value represented by this variable.
Private Attributes
QSharedPointer< OidVariable > new_value
The new value for the variable. Used during a Set operation.
Additional Inherited Members
Public Types inherited from agentxcpp::AbstractVariable
enum testset_result_t {
noError = 0, genErr = 5, noAccess = 6, wrongType = 7,
wrongLength = 8, wrongValue = 10, noCreation = 11, inconsistentValue = 12,
resourceUnavailable = 13, notWritable = 17, inconsistentName = 18
}
Result type for the TestSet validation.
Detailed Description
Represents an SNMP OBJECT-IDENTENTIFIER variable.
The agentXcpp library distinguishes between Oid and OidVariable types. An Oid is a sequence of numbers, while OidVariable is an SNMP variable representing an Oid. That means, that Get and Set requests are possible on OidVariable's, but not on Oid's.
Definition at line 41 of file OidVariable.hpp.
Constructor & Destructor Documentation
OidVariable::OidVariable (const Oid & o)
Initialize an OidVariable object with an Oid.
The internal value is set to the provided Oid.
Parameters
o The initial Oid.
Exceptions
None.
Definition at line 29 of file OidVariable.cpp.
agentxcpp::OidVariable::OidVariable () inline
Default constructor.
Initialize the value to the null Oid.
Definition at line 74 of file OidVariable.hpp.
OidVariable::OidVariable (binary::const_iterator & pos, const binary::const_iterator & end, bool big_endian = true)
Parse Constructor.
This constructor parses the serialized form of the object. It takes an iterator, starts parsing at the position of the iterator and advances the iterator to the position right behind the object.
The constructor expects valid data from the stream; if parsing fails, parse_error is thrown. In this case, the iterator position is undefined.
Parameters
pos Iterator pointing to the current stream position. The iterator is advanced while parsing.
end Iterator pointing one element past the end of the current stream. This is needed to avoid buffer overrun.
big_endian Whether the input stream is in big endian format.
Definition at line 106 of file OidVariable.cpp.
Member Function Documentation
virtual void agentxcpp::OidVariable::handle_cleanupset () inline virtual
Handle a CleanupSet request.
This function calls perform_cleanupset() with the internal value of new_value (which was updated by the last handle_testset() invocation).
Implements agentxcpp::AbstractVariable.
Definition at line 200 of file OidVariable.hpp.
References perform_cleanupset().
virtual bool agentxcpp::OidVariable::handle_commitset () inline virtual
Handle a CommitSet request.
This function calls perform_commitset() with the internal value of new_value (which was updated by the last handle_testset() invocation).
Returns
The return value of perform_commitset().
Implements agentxcpp::AbstractVariable.
Definition at line 218 of file OidVariable.hpp.
References perform_commitset().
virtual void agentxcpp::OidVariable::handle_get () inline virtual
Handle a Get Request.
This function calls perform_get() to update the internal value.
Implements agentxcpp::AbstractVariable.
Definition at line 154 of file OidVariable.hpp.
References perform_get().
virtual testset_result_t agentxcpp::OidVariable::handle_testset (QSharedPointer< AbstractVariable > _v) inline virtual
Handle a TestSet request.
This function converts the argument, stores it in new_value and then calls perform_testset() with the internal value of new_value. If conversion fails, AbstractVariable::wrongType is returned and perform_testset() is not called.
Parameters
_v The new value for the variable.
Returns
AbstractVariable::wrongType if the conversion fails. Otherwise, the result of perform_testset() is returned.
Implements agentxcpp::AbstractVariable.
Definition at line 171 of file OidVariable.hpp.
References perform_testset(), and agentxcpp::AbstractVariable::wrongType.
virtual bool agentxcpp::OidVariable::handle_undoset () inline virtual
Handle an UndoSet request.
This function calls perform_undoset() with the internal value of new_value (which was updated by the last handle_testset() invocation).
Returns
The return value of perform_undoset().
Implements agentxcpp::AbstractVariable.
Definition at line 236 of file OidVariable.hpp.
References perform_undoset().
virtual void agentxcpp::OidVariable::perform_cleanupset (const Oid & _v) inline virtual
Perform an SNMP CleanupSet request.
This method is invoked when an SNMP CleanupSet request is received. It shall release any resources allocated by perform_testset().
The default implementation does nothing. If no action is required to perform the CleanupSet operation, this method need not be overridden.
Parameters
_v The value to which the variable was (possibly) set.
Definition at line 208 of file OidVariable.hpp.
Referenced by handle_cleanupset().
virtual bool agentxcpp::OidVariable::perform_commitset (const Oid & _v) inline virtual
Perform an SNMP CommitSet request.
This method is invoked when an SNMP CommitSet request is received. It shall perform the actual write operation.
The default implementation returns false to indicate that the operation failed. To implement a writeable SNMP variable this method must be overridden.
Parameters
_v The value which shall be written.
Returns
True if the operation succeeded, false otherwise.
Definition at line 226 of file OidVariable.hpp.
Referenced by handle_commitset().
virtual void agentxcpp::OidVariable::perform_get () inline virtual
Perform a Get request.
This method is invoked when an SNMP Get request is received. It should update the internal value v.
Definition at line 162 of file OidVariable.hpp.
Referenced by handle_get().
virtual testset_result_t agentxcpp::OidVariable::perform_testset (const Oid & _v) inline virtual
Perform an SNMP TestSet request.
This method is invoked when an SNMP TestSet request is received. It shall check whether a Set operation is possible for the variable. It shall acquire the resources needed to perform the Set operation (but the Set operation shall not yet be performed).
The default implementation returns AbstractVariable::noAccess to indicate that this is a read-only variable. Thus, for read-only variables this method need not be overridden.
Parameters
_v The new value provided by the master agent.
Returns
The result of the check (this is reported to the master agent).
Definition at line 190 of file OidVariable.hpp.
References agentxcpp::AbstractVariable::noAccess.
Referenced by handle_testset().
virtual bool agentxcpp::OidVariable::perform_undoset (const Oid & _v) inline virtual
Perform an SNMP UndoSet request.
This method is invoked when an SNMP UndoSet request is received. It shall undo whatever perform_commitset() performed. It shall also release all resources allocated by perform_testset(), because perform_cleanupset() will not be called afterwards.
The default implementation returns false to indicate that the operation failed. It is strongly recommended that writeable variables override this method.
A default implementation is provided to allow implementing read-only variables.
Parameters
_v The value just set by perform_commitset().
Returns
True on success, false otherwise.
Definition at line 245 of file OidVariable.hpp.
Referenced by handle_undoset().
binary OidVariable::serialize () const virtual
Encode the object as described in RFC 2741, section 5.4.
This function uses big endian.
Implements agentxcpp::AbstractVariable.
Definition at line 35 of file OidVariable.cpp.
Referenced by agentxcpp::GetPDU::serialize(), agentxcpp::GetNextPDU::serialize(), agentxcpp::RemoveAgentCapsPDU::serialize(), agentxcpp::UnregisterPDU::serialize(), agentxcpp::OpenPDU::serialize(), agentxcpp::AddAgentCapsPDU::serialize(), agentxcpp::RegisterPDU::serialize(), agentxcpp::GetBulkPDU::serialize(), and agentxcpp::Varbind::serialize().
void agentxcpp::OidVariable::setValue (const Oid & _value) inline
Set the value.
Parameters
_value The new value.
Definition at line 91 of file OidVariable.hpp.
virtual Oid agentxcpp::OidVariable::toOid () const inline virtual
Convert the value to an OID.
The conversion is done according to RFC 2578, 7.7. "Mapping of the INDEX clause". First, the length of the OID (i.e. the number of subid's it has) is converted to a subid. Then, each subid of the value is appended.
Todo:
Support fixed-length OIDs according to RFC 2578, 7.7. "Mapping of the INDEX clause".
Returns
The generated Oid.
Exceptions
None.
Implements agentxcpp::AbstractVariable.
Definition at line 130 of file OidVariable.hpp.
References v.
Oid agentxcpp::OidVariable::value () inline
Get the current value.
Returns
The value.
Definition at line 83 of file OidVariable.hpp.
References v.
Referenced by agentxcpp::AddAgentCapsPDU::AddAgentCapsPDU(), agentxcpp::GetBulkPDU::GetBulkPDU(), agentxcpp::GetNextPDU::GetNextPDU(), agentxcpp::OpenPDU::OpenPDU(), agentxcpp::RegisterPDU::RegisterPDU(), agentxcpp::RemoveAgentCapsPDU::RemoveAgentCapsPDU(), agentxcpp::UnregisterPDU::UnregisterPDU(), and agentxcpp::Varbind::Varbind().
Member Data Documentation
QSharedPointer<OidVariable> agentxcpp::OidVariable::new_value private
The new value for the variable. Used during a Set operation.
The Set operation is performed in up to four steps (TestSet, CommitSet, CleanupSet, UndoSet). Only the TestSet step actually receives the new value. This value is stored here so that it can be delivered to perform_commitset(), perform_undoset() and perform_cleanupset().
Definition at line 54 of file OidVariable.hpp.
Oid agentxcpp::OidVariable::v protected
The value represented by this variable.
Definition at line 47 of file OidVariable.hpp.
Referenced by toOid(), and value().
The documentation for this class was generated from the following files:
/home/tanjeff/projekte/agentxcpp/deliv/agentxcpp-0.3/src/OidVariable.hpp
/home/tanjeff/projekte/agentxcpp/deliv/agentxcpp-0.3/src/OidVariable.cpp