AgentXcpp: agentxcpp Namespace Reference
agentxcpp Namespace Reference
Classes
class AbstractValue
This class represents a value.
class AbstractVariable
Base class for SNMP variables.
class AddAgentCapsPDU
Represents an AddAgentCaps-PDU.
class binary
A type representing a contigous byte stream.
class CleanupSetPDU
Represents an CleanupSet-PDU.
class ClosePDU
This class represents a Close-PDU.
class CommitSetPDU
Represents an CommitSet-PDU.
class Counter32Value
Represents an Counter32 as described in RFC 2741.
class Counter64Value
Represents an Counter64 as descibed in RFC 2741.
class parse_error
Exception for parse errors.
class inval_param
Exception for invalid parameter.
class version_error
Exception for reception of PDU with invalid version number.
class disconnected
Exception to indicate a disconnected state.
class timeout_error
Exception to indicate a timeout.
class network_error
Exception to indicate a network error.
class internal_error
Exception to indicate an internal error.
class master_is_unable
Exception to indicate that the master agent was unable to process a request.
class master_is_unwilling
Exception to indicate that the master agent was not willing to process a request.
class duplicate_registration
Exception to indicate that a MIB region was registered twice with the same priority.
class unknown_registration
Exception to indicate that a MIB region registration was not found.
class generic_error
Exception to indicate that obtaining the value of an SNMP variable failed.
class unsupported_context
Exception to indicate that the master agent does not support the context.
class Gauge32Value
Represents a Gauge32 as descibed in RFC 2741.
class GetBulkPDU
Represents an GetBulk-PDU.
class GetNextPDU
Represents an GetNext-PDU.
class GetPDU
Represents an Get-PDU.
class IndexAllocatePDU
Represents a IndexAllocate-PDU.
class IndexDeallocatePDU
Represents a IndexDeallocate-PDU.
class IntegerValue
Represents an Integer as described in RFC 2741.
class IpAddressValue
Represents an IP address as described in RFC 2741, section 5.4.
class MasterProxy
This class represents the master agent in a subagent program.
class NotifyPDU
Represents an Notify-PDU.
class OctetStringValue
Represents an Octet String as described in RFC 2741, section 5.3.
class OidValue
Represents an SNMP object identifier (OID).
class OpaqueValue
Represents an Opaque object as described in RFC 2741, section 5.4.
class OpenPDU
Represents an Open-PDU.
class PDU
The base class of all PDU's.
class PDUwithContext
class PingPDU
Represents a Ping-PDU.
class RegisterPDU
This class represents a Register-PDU.
class RemoveAgentCapsPDU
Represents an RemoveAgentCaps-PDU.
class ResponsePDU
Represents an Response-PDU.
class TestSetPDU
Represents an TestSet-PDU.
class TimeTicksValue
Represents an TimeTicks as described in RFC 2741.
class UndoSetPDU
Represents an UndoSet-PDU.
class UnixDomainConnector
Connect to a unix domain socket.
class UnregisterPDU
This class represents an Unregister-PDU.
class varbind
Represents a VarBind according to RFC 2741, section 5.4.
class Variable
Class template to implement primitive SNMP variables.
Enumerations
enum generic_trap_t {
coldStart = 0, warmStart = 1, linkDown = 2, linkUp = 3,
authenticationFailure = 4, egpNeighborLoss = 5, enterpriseSpecific = 6
}
The allowed values for specific-trap (SNMPv1 trap).
Functions
std::ostream & operator<< (std::ostream &out, const binary &data)
Output operator for binary.
TimeTicksValue processUpTime ()
Calculate the uptime of the current process.
OidValue generate_v1_snmpTrapOID (generic_trap_t generic_trap, boost::optional< uint32_t > specific_trap=boost::optional< uint32_t >())
Create snmpTrapOID.0 value from SNMPv1 trap data.
std::ostream & operator<< (std::ostream &out, const agentxcpp::OidValue &o)
The output operator for the OidValue class.
uint64_t read64 (binary::const_iterator &pos, bool big_endian)
void write64 (binary &serialized, uint64_t value)
Write a 64-bit value into a string.
uint32_t read32 (binary::const_iterator &pos, bool big_endian)
void write32 (binary &serialized, uint32_t value)
Write a 32-bit value into a string.
uint16_t read16 (binary::const_iterator &pos, bool big_endian)
void write16 (binary &serialized, uint16_t value)
Write a 16-bit value into a string.
Enumeration Type Documentation
enum agentxcpp::generic_trap_t
The allowed values for specific-trap (SNMPv1 trap).
According to RFC 1157, these values can be used for the generic-trap field in SNMPv1 Traps.
Enumerator:
coldStart
warmStart
linkDown
linkUp
authenticationFailure
egpNeighborLoss
enterpriseSpecific
Definition at line 53 of file helpers.hpp.
Function Documentation
OidValue agentxcpp::generate_v1_snmpTrapOID (generic_trap_t generic_trap, boost::optional< uint32_t > specific_trap = boost::optional<uint32_t>())
Create snmpTrapOID.0 value from SNMPv1 trap data.
Each notification must have an snmpTrapOID.0 object. In SNMPv1 no notifications were available; traps were used instead. This function takes parameters which would be present in an SNMPv1 trap and converts them to the corresponding an snmpTrapOID.0 value, which can be included in a notification. The master agent extracts the SNMPv1 trap information while generating a trap (only if sending an SNMPv1 trap, of course).
The conversion is done according to RFC 1908, 3.1.2 "SNMPv1 -> SNMPv2".
Parameters
generic_trap The type of trap. If it is enterpriseSpecific, then the parameter specific_trap must also be given.
specific_trap Only used if generic_trap is enterpriseSpecific. It can be any value specific to the subagent.
Returns
The value of the snmpTrapOID.0 object.
Exceptions
inval_param If the generic_trap parameter has an invalid value or if generic_trap is enterpriseSpecific and specific_trap was not given.
Definition at line 56 of file helpers.cpp.
References authenticationFailure, coldStart, egpNeighborLoss, enterpriseSpecific, linkDown, linkUp, and warmStart.
std::ostream& agentxcpp::operator<< (std::ostream & out, const binary & data) inline
Output operator for binary.
Definition at line 42 of file binary.hpp.
std::ostream & agentxcpp::operator<< (std::ostream & out, const agentxcpp::OidValue & o)
The output operator for the OidValue class.
Object identifiers (OidValue objects) can be output as follows:
OidValue led_state(enterprises_oid, "1.3.3.1");
cout << "LED state OID: " << led_state << endl;
The last line will output "LED state OID: .1.3.6.1.4.1.3.3.1".
Parameters
out The stream to which to write the output.
o The OID to output.
Returns
The 'out' parameter.
Definition at line 87 of file OidValue.cpp.
TimeTicksValue agentxcpp::processUpTime ()
Calculate the uptime of the current process.
This function calculates the uptime of the current process, in hundreths of a second. The result may be given as sysUpTime.0. parameter to agentxcpp::MasterProxy::send_notification(const boost::optional<TimeTicksValue>&, const OidValue&, const vector<varbind>&).
The time is measured using a global variable which is initialized to the current time just be before main() starts.
Returns
The current uptime, in hundreths of a second.
Definition at line 43 of file helpers.cpp.
uint16_t agentxcpp::read16 (binary::const_iterator & pos, bool big_endian) inline
Definition at line 120 of file util.hpp.
Referenced by agentxcpp::GetBulkPDU::GetBulkPDU(), agentxcpp::ResponsePDU::ResponsePDU(), and agentxcpp::varbind::varbind().
uint32_t agentxcpp::read32 (binary::const_iterator & pos, bool big_endian) inline
Definition at line 83 of file util.hpp.
Referenced by agentxcpp::Counter32Value::Counter32Value(), agentxcpp::UnixDomainConnector::do_receive(), agentxcpp::Gauge32Value::Gauge32Value(), agentxcpp::IntegerValue::IntegerValue(), agentxcpp::IpAddressValue::IpAddressValue(), agentxcpp::OctetStringValue::OctetStringValue(), agentxcpp::PDU::parse_pdu(), agentxcpp::PDU::PDU(), agentxcpp::RegisterPDU::RegisterPDU(), agentxcpp::ResponsePDU::ResponsePDU(), agentxcpp::TimeTicksValue::TimeTicksValue(), and agentxcpp::UnregisterPDU::UnregisterPDU().
uint64_t agentxcpp::read64 (binary::const_iterator & pos, bool big_endian) inline
Definition at line 33 of file util.hpp.
Referenced by agentxcpp::Counter64Value::Counter64Value().
void agentxcpp::write16 (binary & serialized, uint16_t value) inline
Write a 16-bit value into a string.
Parameters
serialized The string to which the value is appended.
value The value which is appended to the string.
Definition at line 145 of file util.hpp.
Referenced by agentxcpp::GetBulkPDU::serialize(), and agentxcpp::ResponsePDU::serialize().
void agentxcpp::write32 (binary & serialized, uint32_t value) inline
Write a 32-bit value into a string.
Parameters
serialized The string to which the value is appended.
value The value which is appended to the string.
Definition at line 111 of file util.hpp.
Referenced by agentxcpp::PDU::add_header(), agentxcpp::OctetStringValue::serialize(), agentxcpp::IntegerValue::serialize(), agentxcpp::TimeTicksValue::serialize(), agentxcpp::Gauge32Value::serialize(), agentxcpp::Counter32Value::serialize(), agentxcpp::UnregisterPDU::serialize(), agentxcpp::RegisterPDU::serialize(), and agentxcpp::ResponsePDU::serialize().
void agentxcpp::write64 (binary & serialized, uint64_t value) inline
Write a 64-bit value into a string.
Parameters
serialized The string to which the value is appended.
value The value which is appended to the string.
Definition at line 69 of file util.hpp.
Referenced by agentxcpp::Counter64Value::serialize().