#
# Copyright 2011-2016 Tanjeff-Nicolai Moos <tanjeff@cccmz.de>
#
# This file is part of the agentXcpp library.
#
# AgentXcpp is free software: you can redistribute it and/or modify
# it under the terms of the AgentXcpp library license, version 1, which 
# consists of the GNU General Public License and some additional 
# permissions.
#
# AgentXcpp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# See the AgentXcpp library license in the LICENSE file of this package 
# for more details.
#

# Get the environment from the SConscript above
Import('env')

#################################################
## API documentation

api = env.Doxygen('api.doxyfile',
                  DOXYPROJECTNUMBER="Version: " + env['revision'])
env.Clean(api, "api")

api_install = env.Install(env['docdir'], "api")
env.Clean(api_install, env['docdir'])


#################################################
## Internals documentation (without installation target):

internals = env.Doxygen('internals.doxyfile',
                        DOXYPROJECTNUMBER="Version: " + env['revision'])
env.Clean(internals, "internals")


#################################################
## The default targets for this directory
Alias("install", env['docdir'])
env.Default(api, internals)
