AgentXcpp: /home/tanjeff/projekte/agentxcpp/src/helper.hpp File Reference
/home/tanjeff/projekte/agentxcpp/src/helper.hpp File Reference
#include "types.hpp"
Functions
uint32_t read32 (data_t::const_iterator &pos, bool big_endian)
void write32 (data_t &serialized, uint32_t value)
Write a 32-bit value into a string.
uint16_t read16 (data_t::const_iterator &pos, bool big_endian)
void write16 (data_t &serialized, uint16_t value)
Write a 16-bit value into a string.
Function Documentation
uint16_t read16 (data_t::const_iterator & pos, bool big_endian) [inline]
Definition at line 62 of file helper.hpp.
Referenced by agentxcpp::GetBulkPDU::GetBulkPDU(), agentxcpp::ResponsePDU::ResponsePDU(), and agentxcpp::varbind::varbind().
uint32_t read32 (data_t::const_iterator & pos, bool big_endian) [inline]
Definition at line 25 of file helper.hpp.
Referenced by agentxcpp::PDU::parse_pdu(), agentxcpp::PDU::PDU(), agentxcpp::connector::receive_callback(), agentxcpp::RegisterPDU::RegisterPDU(), and agentxcpp::ResponsePDU::ResponsePDU().
void write16 (data_t & serialized, uint16_t value) [inline]
Write a 16-bit value into a string.
Parameters:
serialized The string to which the value is appended.
value The value which is appended to the string.
Definition at line 87 of file helper.hpp.
Referenced by agentxcpp::GetBulkPDU::serialize(), and agentxcpp::ResponsePDU::serialize().
void write32 (data_t & serialized, uint32_t value) [inline]
Write a 32-bit value into a string.
Parameters:
serialized The string to which the value is appended.
value The value which is appended to the string.
Definition at line 53 of file helper.hpp.
Referenced by agentxcpp::PDU::add_header(), agentxcpp::RegisterPDU::serialize(), and agentxcpp::ResponsePDU::serialize().