#
# Copyright 2011 Tanjeff-Nicolai Moos <tanjeff@cccmz.de>
#
# This file is part of the agentXcpp library.
#
# AgentXcpp is free software: you can redistribute it and/or modify
# it under the terms of the AgentXcpp library license, version 1, which 
# consists of the GNU General Public License and some additional 
# permissions.
#
# AgentXcpp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# See the AgentXcpp library license in the LICENSE file of this package 
# for more details.
#

import os


# Build the library:
agentxcpp = SharedLibrary('agentxcpp', Glob('*.cpp'))


# Fetch prefix from ENV or use default:
if os.environ.has_key('PREFIX'):
    prefix = os.environ['PREFIX']
else:
    prefix = "/usr/local"

# Install library (the "#" means: path is relative to
# top-level build dir)
libdir = "#" + prefix + "/lib"
Install(libdir, agentxcpp)
Alias("install", libdir)

# Install headers
includedir = "#" + prefix + "/include"
Install(includedir, Glob('*.h'))
Alias("install", includedir)
