#
# Copyright 2011 Tanjeff-Nicolai Moos <tanjeff@cccmz.de>
#
# This file is part of the agentXcpp library.
#
# AgentXcpp is free software: you can redistribute it and/or modify
# it under the terms of the AgentXcpp library license, version 1, which 
# consists of the GNU General Public License and some additional 
# permissions.
#
# AgentXcpp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# See the AgentXcpp library license in the LICENSE file of this package 
# for more details.
#

# Get the environment from the SConscript above
Import('env')


# Build the library:
agentxcpp = env.SharedLibrary('agentxcpp', Glob('*.cpp'))


# Install library (the "#" means: path is relative to
# top-level build dir)
Install(env['libdir'], agentxcpp)
Alias("install", env['libdir'])

# Install headers
Install(env['includedir'], Glob('*.h'))
Alias("install", env['includedir'])


# What to build by default
Default(agentxcpp)
